print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/wvanleunen/Documents/T/TreasureHunt4/Assets/maurice_unity_241016/Maurice/maurice.mb"`)
{		
	file -o "/Users/wvanleunen/Documents/T/TreasureHunt4/Assets/maurice_unity_241016/Maurice/maurice.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/wvanleunen/Documents/T/TreasureHunt4/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";


system ("rm \"/Users/wvanleunen/Documents/T/TreasureHunt4/Temp/CommandPipe\"");

$donepipeKill = `fopen "/Users/wvanleunen/Documents/T/TreasureHunt4/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
